### ISSUE TITLE
go can not fetch the right verison of open-ness/common/log

### ISSUE THREAD

**Issue by hjwoohakimwhj** [open-ness/common#3]
Hi ! When I install openness edgecontroller and run 'make build', it shows that 'go: github.com/open-ness/common/log@v0.0.0-20191030124530-f3b0c431ec77: invalid pseudo-version: does not match version-control timestamp (2019-10-30T13:45:30Z)'. Could you please tell me how to fix it? Thanks a lot

go.mod:
require {
        github.com/open-ness/common/proxy v0.0.0-20191031150002-ec9a498acb69
        github.com/open-ness/common/log v0.0.0-20191030124530-f3b0c431ec77
}

**Comment by amr-mokhtar** [comment]
Hi hjwoohakimwhj, this should have been fixed by [OpenNESS 19.09.01 Release Update](https://github.com/open-ness/common/releases/tag/openness_190901_2).
